- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - release-notes-jobs-python3
    queue: os-win
